/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 139,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1255,

					NT_OFFSET = 139,
					SCOPE_UBOUND = 326,
					SCOPE_SIZE = 327,
					LA_STATE_OFFSET = 18450,
					MAX_LA = 1,
					NUM_RULES = 951,
					NUM_TERMINALS = 139,
					NUM_NON_TERMINALS = 438,
					NUM_SYMBOLS = 577,
					START_STATE = 999,
					EOFT_SYMBOL = 64,
					EOLT_SYMBOL = 64,
					ACCEPT_ACTION = 18449,
					ERROR_ACTION = 18450;
}
